---
title: "CV"

format: html

page-layout: full
title-block-banner: true

page-navigation: true
toc: true
toc-title: "Outline"
---

## Education

Ph.D. Candidate in Neuroscience & Human Performance (2026 exp) <br> Indiana University Bloomington

M.S. in Applied Statistics, Indiana University Bloomington <br> M.S. in Exercise Physiology, Indiana University Bloomington <br> B.S. in Exercise Science, Indiana University Bloomington

## Research Experience

2017 - 2022 <br> Biostatistics Associate <br> Biostatistics Consulting Center, Department of Epidemiology and Biostatistics, School of Public Health, Indiana University Bloomington

2020 - 2021 <br> Research Assistant <br> The NCAA-DoD Concussion Assessment, Research, and Education (CARE) Consortium <br> Department of Epidemiology and Biostatistics, School of Public Health, Indiana University

2014 - 2016 <br> Consulting Associate <br> Indiana Statistical Consulting Center, Department of Statistics, Indiana University Bloomington

2007 - 2009 <br> Research Scholar <br> Counsilman Center for the Science of Swimming, Department of Kinesiology, Indiana University Bloomington

## Teaching

2020 <br> Associate Instructor (Neuroscience) <br> Program in Neuroscience, Indiana University Bloomington

2019 <br> Adjunct Lecturer (Motor Learning) <br> Department of Kinesiology, Indiana University Bloomington

2014 - 2016 <br> Associate Instructor (Statistical Literacy) <br> Department of Statistics, Indiana University Bloomington

2013 <br> Teaching Assistant (Statistical Literacy) <br> Department of Statistics, Indiana University Bloomington

2009 - 2012 <br> Associate Instructor (Exercise Physiology) <br> Department of Kinesiology, Indiana University Bloomington

## Publications

Varley, Thomas F., Daniel Havert, Leandro Fosque, Abolfazl Alipour, Naruepon Weerawongphrom, **Hiroki Naganobori**, Lily O’Shea, Maria Pope, and John Beggs. 2024. “The Serotonergic Psychedelic n,n-Dipropyltryptamine Alters Information-Processing Dynamics in in Vitro Cortical Neural Circuits.” *Network Neuroscience* 8 (4): 1421–38. <https://doi.org/10.1162/netn_a_00408>.

Seifert, Jack, Alok Shah, Jaroslaw Harezlak, **Hiroki Naganobori**, Jared Muench, Steven Rowson, Stefan Duma, et al. 2022. “Elevated Rate of Head Impacts at Time of Injury in Concussed NCAA Division i American Football Players: Findings from the NCAA-DoD CARE Consortium.” In *BRAIN INJURY*, 36:65–66.

Stager, Joel M., Andrew C. Cornett, and **Hiroki Naganobori**. 2013. “Vertical Head Velocity During Worst-Case Scenario Swim Starts.” *International Journal of Aquatic Research and Education* 7 (3). <https://doi.org/10.25035/ijare.07.03.05>.

Cornett, Andrew C., **Hiroki Naganobori**, and Joel M. Stager. 2012. “Intra-Individual Head Depth Variability During the Competitive Swim Start.” *International Journal of Aquatic Research and Education* 6 (4). <https://doi.org/10.25035/ijare.06.04.09>.
